version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: cra1ger/foodgram_backend:v1
    restart: always
    volumes:
      - static_value:/app/static/data/arial.ttf
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    
  frontend:
    image: cra1ger/foodgram_frontend:v1
    volumes:
      - ../frontend/:/app/result_build/
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/usr/share/fonts/arial.ttf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  postgres_db:
  static_value:
  media_value: