# Generated by Django 3.2.19 on 2023-06-05 15:47

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Список покупок',
            },
        ),
        migrations.RemoveField(
            model_name='shoppingcard',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='shoppingcard',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ['-id'], 'verbose_name': 'Ингредиенты', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientsrecipes',
            options={'ordering': ['-recipes'], 'verbose_name': 'Ингредиенты и рецепты', 'verbose_name_plural': 'Ингредиенты и рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['-id'], 'verbose_name': 'Рецепты', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['-id'], 'verbose_name': 'Теги', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='tagsrecipes',
            options={'ordering': ['-recipes'], 'verbose_name': 'Теги и рецепты', 'verbose_name_plural': 'Теги и рецепты'},
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='coockeng_time',
        ),
        migrations.AddField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=1, help_text='Время приготовления', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(help_text='Вкусная картинка', upload_to='media/recipes/', verbose_name='Вкусная картинка'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(help_text='Название', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='Цвет тега', image_field=None, max_length=7, samples=None, unique=True, verbose_name='Цвет тега'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(help_text='Теги', max_length=50, unique=True, verbose_name='Теги'),
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('recipes', 'user'), name='Favorites_unique'),
        ),
        migrations.AddConstraint(
            model_name='ingredients',
            constraint=models.UniqueConstraint(fields=('measurement_unit', 'name'), name='Ingredients_unique'),
        ),
        migrations.AddConstraint(
            model_name='ingredientsrecipes',
            constraint=models.UniqueConstraint(fields=('ingredients', 'recipes'), name='IngredientsRecipes_unique'),
        ),
        migrations.AddConstraint(
            model_name='recipes',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='Recipes_unique'),
        ),
        migrations.AddConstraint(
            model_name='tags',
            constraint=models.UniqueConstraint(fields=('color', 'name', 'slug'), name='Tags_unique'),
        ),
        migrations.AddConstraint(
            model_name='tagsrecipes',
            constraint=models.UniqueConstraint(fields=('tags', 'recipes'), name='TagsRecipes_unique'),
        ),
        migrations.DeleteModel(
            name='ShoppingCard',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='recipes.recipes', verbose_name='Рецепты'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('recipes', 'user'), name='Recipe_cart_unique'),
        ),
    ]
